server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/osahaneat
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#    properties:
#      hibernate:
#        naming:
#          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

logging:
  level:
    root: warn

jwt:
  privateKey: FytGeqhKcSeqveDDzHSmx/FZHQuEYT6w5VqEtVoZdaU=
